name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deno:
    name: 'Deno Solutions'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
      - run: deno test --allow-read
  rust:
    name: 'Rust Solutions'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test
